dj4e_2/ad/urls.py
from django.urls import path
from . import views

app_name='ads'
urlpatterns = [
	path('', views.AdListView.as_view(), name='main'),
	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad-detail'),
	path('ad/create/', views.AdCreateView.as_view(), name='ad-create'),
	path('ad/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad-update'),
	path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad-delete'),
	path('pic_picture/<int:pk>/', views.stream_file, name='pic_picture'),
]

dj4e_2/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
import os
from django.views.static import serve


urlpatterns = [
	path('', include('home.urls')),
    path('myarts/', include('myarts.urls')),
    path('ads/', include('ad.urls')),
    path('forum/', include('forum.urls')),
    path('jsonapp/', include('jsonapp.urls')),
    # path('pics/', include('pics.urls')), replaced by ad app
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('register/', user_views.Register.as_view(), name="register"),
]
# server favicon
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            "path":"favicon.ico",
            "document_root": os.path.join(BASE_DIR, "home/static"),
        } 
        ),

]

dj4e_2/jsonapp/urls.py
from django.urls import path
from . import views
import os
from django.views.static import serve
from django.conf.urls import url


app_name = "jsonapp"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
urlpatterns = [
	path('', views.index, name='main'),
	path('check', views.check, name="check"),
	path('talk', views.TalkMain.as_view(), name='talk'),
	path('messages', views.TalkMessages.as_view(), name='messages'),
	url(r'static/(?P<path>.*)$', serve, 
		{'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
		name='static'
		),
]

dj4e_2/jsonapp/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Message(models.Model):
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

dj4e_2/jsonapp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import Message
from django.contrib.humanize.templatetags.humanize import naturaltime
import time

# Create your views here.
def index(request):
	time.sleep(2)
	stuff={
	"first": "This is firist",
	"second": "This is second"
	}
	return JsonResponse(stuff)

class TalkMain(LoginRequiredMixin, View):
	def get(self, request):
		return render(request, 'jsonapp/talk.html')

	def post(self, request) :
		message = Message(text=request.POST['message'], owner=request.user)
		message.save()
		return redirect(reverse('jsonapp:talk'))


class TalkMessages(LoginRequiredMixin, View) :
	def get(self, request):
		messages = Message.objects.all().order_by('-created_at')[:10]
		results = []
		for message in messages:
			result = [message.text, naturaltime(message.created_at), message.owner.username]
			results.append(result)
		return JsonResponse(results, safe=False)


def check(request):
	return render(request, "jsonapp/check.html")

dj4e_2/jsonapp/templates/jsonapp/check.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


</head>
<body>
	this works? This is working perfectly fine 
	<div id="chatcontent">
		<img src="{% url 'jsonapp:static' 'spinner.gif' %}" alt="Loading..."/>
	</div>
	<script type="text/javascript">
		function updateMsg() {
    	console.log('Requesting JSON'); 
    	$.getJSON('{% url 'jsonapp:messages' %}', function(data){
        console.log('JSON', data);
        $('#chatcontent').empty();
        for (var i =0; i<data.length; i++){
        	block = data[i];
        	$("#chatcontent").append('<p>'+ block[0] +
        		"<br/>&nbsp;&nbsp;" + block[1]+"</p>\n");
        }
        setTimeout('updateMsg()', 4000);
    });
}

$(document).ready(function() {
	$.ajaxSetup({ cache: false });
    setTimeout('updateMsg()', 2000);
});

	</script>
</body>
</html>

dj4e_2/jsonapp/templates/jsonapp/talk.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
<h1>Chat</h1>
<form method="post">
{% csrf_token %}
<input type="text" name="message" size="40"/><br>
<input type="submit" value="Chat"/> 
<input type="submit" name="reset" value="Reset"/> 
<a href="{% url 'jsonapp:main' %}" target="_blank">Cancel</a>
</p>
</form>

<div id="chatcontent">
<img src="{% url 'jsonapp:static' 'spinner.gif' %}" alt="Loading..."/>
</div>
</div>

<script type="text/javascript">
function updateMsg() {
    console.log('Requesting JSON'); 
    $.getJSON('{% url 'jsonapp:messages' %}', function(rowz){
        console.log('JSON', rowz);
        $('#chatcontent').empty();
        for (var i = 0; i < rowz.length; i++) {
          arow = rowz[i];
          $('#chatcontent').append('<p>'+arow[0] +
              '<br/>&nbsp;'+arow[1]+"&nbsp;by&nbsp;" + arow[2] +"</p>\n");
        }
        setTimeout('updateMsg()', 4000);
    });
}

$(document).ready(function() {
	$.ajaxSetup({ cache: false });
    setTimeout('updateMsg()', 2000);
});

// Make sure JSON requests are not cached

</script>
{% endblock %}