dj4e_2/ad/urls.py
from django.urls import path
from . import views

app_name='ads'
urlpatterns = [
	path('', views.AdListView.as_view(), name='main'),
	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad-detail'),
	path('ad/create/', views.AdCreateView.as_view(), name='ad-create'),
	path('ad/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad-update'),
	path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad-delete'),
	path('pic_picture/<int:pk>/', views.stream_file, name='pic_picture'),
]

dj4e_2/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
import os
from django.views.static import serve


urlpatterns = [
	path('', include('home.urls')),
    path('myarts/', include('myarts.urls')),
    path('ads/', include('ad.urls')),
    path('forum/', include('forum.urls')),
    path('jsonapp/', include('jsonapp.urls')),
    # path('pics/', include('pics.urls')), replaced by ad app
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('register/', user_views.Register.as_view(), name="register"),
]
# server favicon
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            "path":"favicon.ico",
            "document_root": os.path.join(BASE_DIR, "home/static"),
        } 
        ),

]

dj4e_2/forum/urls.py
from django.urls import path
from . import views



app_name = 'forum'
urlpatterns = [
	path('jsonfun/', views.index, name='jsonfun'),
	path('', views.ForumListView.as_view(), name='main'),
	path('create/', views.ForumCreateView.as_view(), name='forum-create'),
	path('update/<int:pk>/', views.ForumUpdateView.as_view(), name='forum-update'),
	path('<int:pk>/delete/', views.ForumDeleteView.as_view(), name='forum-delete'),
	path('<int:pk>/', views.ForumDetailView.as_view(), name='forum-detail'),
	path('<int:pk>/comment', 
        views.CommentCreateView.as_view(), name='forum-comment-create'),
	path('<int:pk>/comment/delete', views.CommentDeleteView.as_view(), name='comment-delete'),
	path('<int:pk>/like', views.AddLikeView.as_view(), name='forum-like'),
	path('<int:pk>/dislike', views.DeleteLikeView.as_view(), name='forum-dislike'),
]

dj4e_2/forum/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinLengthValidator
# Create your models here.
class Forum(models.Model):
	title = models.CharField(max_length=100,
		validators=[MinLengthValidator(2, "Please enter atleast 2 character")],
		help_text='title for the forum'
		)
	text=models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Like',
		related_name='likes_forum')
	comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment',
		related_name='forum_comments')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title


class Comment(models.Model):
	text = models.TextField(
		validators=[MinLengthValidator(2, "Atleast 2 character comments")]
		)
	forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		if len(self.text) < 15:
			return self.text
		return self.text[:12] + ' ..' 


class Like(models.Model):
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

	class Meta:
		unique_together = ('owner', 'forum')

	def __str__(self) :
		return '%s likes %s'%(self.owner.username, self.forum.title[:10])

	

dj4e_2/forum/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from .models import Comment

class CommentForm(forms.Form):
	comment = forms.CharField(max_length=500, min_length=3, required=True)
	

dj4e_2/forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from myarts.owner import (
	OwnerListView,
	OwnerCreateView,
	OwnerUpdateView,
	OwnerDeleteView,
	OwnerDetailView,
	)
from django.http import JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import CommentForm
from .models import Forum, Comment, Like
from django.urls import reverse_lazy
from django.views import generic
# Create your views here.

def index(request):
	stuff={
	"first": "This is firist",
	"second": "This is second"
	}
	return JsonResponse(stuff)

class ForumListView(OwnerListView):
	model = Forum
	template_name = "forum/forum_list.html"

	def get(self, request):
		forum_list=Forum.objects.all()
		liked_forum = list()
		if request.user.is_authenticated:
			rows = request.user.likes_forum.values('id')
			#  rows of id of liked forum
			likes = [row['id'] for row in rows]
		ctx = {
			'forum_list' : forum_list,
			'likes': likes,
		}
		return render(request, self.template_name, ctx)


class ForumCreateView(OwnerCreateView):
	model = Forum
	fields = ['title', 'text']
	success_url = reverse_lazy('forum:main')


class ForumUpdateView(OwnerUpdateView):
	model = Forum
	fields = ['title', 'text']
	success_url = reverse_lazy('forum:main')

class ForumDeleteView(OwnerDeleteView):
	model = Forum
	success_url = reverse_lazy('forum:main')

class ForumDetailView(OwnerDetailView):
	model = Forum
	template_name = "forum/forum_detail.html"

	def get(self, request, pk):
		f = get_object_or_404(self.model, id=pk)
		comments = Comment.objects.filter(forum=f).order_by('-updated_at')
		comment_form = CommentForm()
		context = {
		'forum':f, 
		'comments':comments, 
		'comment_form':comment_form,
		}
		return render(request, self.template_name, context)


class CommentCreateView(LoginRequiredMixin, View):
	def post(self, request, pk):
		f = get_object_or_404(Forum, id=pk)
		comment_text = Comment(text=request.POST['comment'], owner=request.user, forum=f)
		comment_text.save()
		return redirect(reverse('forum:forum-detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
	model = Comment
	def get_success_url(self, request):
		forum = self.object.forum
		return reverse('forums:forum-detail', args=[forum.id])

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddLikeView(LoginRequiredMixin, View):
	def post(self, request, pk):
		f = get_object_or_404(Forum, id=pk)
		liked_objects = Like(owner=request.user, forum=f)
		try:
			liked_objects.save()
		except IntegrityError as e:
			pass
		return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteLikeView(LoginRequiredMixin, View):
	def post(self, request, pk):
		f = get_object_or_404(Forum, id=pk)
		try:
			Like.objects.get(owner=request.user, forum=f).delete()
		except Like.DoesNotExist as e:
			pass
		return HttpResponse()

dj4e_2/forum/templates/forum/comment_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment }} ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'forum:forum-detail' comment.forum.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

dj4e_2/forum/templates/forum/forum_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete Forum</h1>

<p>Are you sure you want to delete</p>
<p>{{ forum }} ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'forum:main' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

dj4e_2/forum/templates/forum/forum_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
	<div class="content-section">
	{% if forum.owner == user %}
	<span style="float:right; font-size: 2vh;">
		<a href="{% url 'forum:forum-update' forum.id %}"><i class="fa fa-pencil"></i></a>
		<a style="margin-left: 10px;" href="{% url 'forum:forum-delete' forum.id %}"><i class="fa fa-trash"></i></a>
	</span>
	{% endif %}
	<h1>
		{{ forum.title }}
	</h1>
	<hr>
	<p>
		{{ forum.text }}
	</p>
	<p>
		(Posted: {{ forum.created_at|naturaltime }} by {{forum.owner}}) 
	</p>
	<hr>
	{% if user.is_authenticated %}
	<br clear="all"/>
	<p>
	{% load crispy_forms_tags %}
	<form method="post" action="{% url 'forum:forum-comment-create' forum.id %}">
		{% csrf_token %}
		{{ comment_form|crispy }}
		<input type="submit" name="" value="Submit">
		<input type="submit" name="" value="all forums" onclick="window.location.href='{% url 'forum:main' %}'; return false;">

	</form>
	{% endif %}
	{% if comments %}
		{% for comment in comments %}
		<p>
			<article style="border:2px solid pink; padding: 10px;">
			{{comment.owner}}<span style="float:right;">({{ comment.updated_at|naturaltime }})</span><br>
			{{comment.text}}
			{% if comment.owner == user %}
				<a style="float: right;"href="{% url 'forum:comment-delete' comment.id %}">delete</a>
			{% endif %}
			</article>
		</p>
		{% endfor %}
	{% endif %}
</p>
</div>
{% endblock content %}

dj4e_2/forum/templates/forum/forum_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<p>
	<form action="" method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" name="" value="Submit">
		<input type="submit" name="" value="Cancel" onclick="window.location.href='{% url 'forum:main' %}'; return false;">

	</form>
</p>
{% endblock content %}

dj4e_2/forum/templates/forum/forum_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Forum</h1>
<p>
	{% if forum_list %}
	<ul>
		{% for forum in forum_list %}
		<li>
			<a href="{% url 'forum:forum-detail' forum.id %}">{{forum.title}}</a>
			{% if forum.owner == user %}
			(<a href="{% url 'forum:forum-update' forum.id %}">Edit</a> | 
			<a href="{% url 'forum:forum-delete' forum.id %}">Delete</a>)
			{% endif %}
			<!-- Forum-like and Forum-dislike -->
			{% if request.user.is_authenticated %}
			<a href="#" onclick="LikeForum('{% url 'forum:forum-dislike' forum.id %}', {{forum.id}}); return false;" 
			{% if forum.id not in likes %} style="display: none;" {% endif %} id="like_{{forum.id}}">
			<span class="fa-stack" style="vertical-align: middle;">
				<i class="fa fa-thumbs-up fa-stack-1x" style="color: orange;"></i>
			</span>
			
			<a href="#" onclick="LikeForum('{% url 'forum:forum-like' forum.id %}', {{forum.id}}); return false;"
			{% if forum.id in likes %} style="display: none;" {% endif %} id="dislike_{{forum.id}}">
			<span class="fa-stack" style="vertical-align: middle;">
        		<i class="fa fa-thumbs-o-up fa-stack-1x"></i>
        	</span>	
			</a>
         
            {% endif %}

		</li>
		{% endfor %}
	</ul>
	{% else %}
	There are no forum in the database
	{% endif %}
</p>
<p>
	<a href="{% url 'forum:forum-create' %}">Add an forum</a>and
</p>
<script>
	function LikeForum(url, forum_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        console.log(rowz);
        $("#dislike_"+forum_id).toggle();
        $("#like_"+forum_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock content %}