dj4e_2/ad/urls.py
from django.urls import path
from . import views

app_name='ads'
urlpatterns = [
	path('', views.AdListView.as_view(), name='main'),
	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad-detail'),
	path('ad/create/', views.AdCreateView.as_view(), name='ad-create'),
	path('ad/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad-update'),
	path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad-delete'),
	path('pic_picture/<int:pk>/', views.stream_file, name='pic_picture'),
]

dj4e_2/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
import os
from django.views.static import serve


urlpatterns = [
	path('', include('home.urls')),
    path('myarts/', include('myarts.urls')),
    path('ads/', include('ad.urls')),
    path('forum/', include('forum.urls')),
    path('jsonapp/', include('jsonapp.urls')),
    # path('pics/', include('pics.urls')), replaced by ad app
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('register/', user_views.Register.as_view(), name="register"),
]
# server favicon
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            "path":"favicon.ico",
            "document_root": os.path.join(BASE_DIR, "home/static"),
        } 
        ),

]

dj4e_2/myarts/urls.py
from django.urls import path
from . import views

app_name='myarts'
urlpatterns = [
	path('', views.ArticleListView.as_view(), name="article-main"),
	path('article/<int:pk>', views.ArticleDetailView.as_view(), name="article-detail"),
	path('article/create', views.ArticleCreateView.as_view(), name='article-create'),
	path('article/<int:pk>/update', views.ArticleUpdateView.as_view(), name="article-update"),
	path('article/<int:pk>/delete', views.ArticleDeleteView.as_view(), name="article-delete"),
	]

dj4e_2/myarts/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.


class Article(models.Model):
	title = models.CharField(
		max_length=200,
		validators=[MinLengthValidator(2, "Title must be greater than a character")]
		)
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	created_at = models.DateTimeField('Published Date', auto_now_add=True)
	updated_at = models.DateTimeField("Last Updated", auto_now=True)


	def __str__(self):
		return self.title

dj4e_2/myarts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from .owner import (
	OwnerListView, 
	OwnerDetailView, 
	OwnerCreateView, 
	OwnerDeleteView,
	OwnerUpdateView)
from .models import Article

class ArticleListView(OwnerListView):
	model = Article
	ordering = ['-created_at']

class ArticleDetailView(OwnerDetailView):
	model = Article


class ArticleCreateView(OwnerCreateView):
	model = Article
	fields = ['title', 'text']
	success_url = reverse_lazy('myarts:article-main')

class ArticleUpdateView(OwnerUpdateView):
	model = Article
	fields = ["title", "text"]
	success_url = reverse_lazy('myarts:article-main')

class ArticleDeleteView(OwnerDeleteView):
	model = Article
	success_url = reverse_lazy('myarts:article-main')


def index(request):
	return HttpResponse("Hi i am index")

dj4e_2/myarts/templates/myarts/article_confirm_delete.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Delete Article</legend>
				<h2>Are you sure to delete "{{object.title}}"</h2>
				
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
				<a class="btn btn-outline-secondary" href="{% url 'myarts:article-main' %}">cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

dj4e_2/myarts/templates/myarts/article_detail.html
{% extends 'base.html' %}
{% block content %}
	
	<article class="media content-section">
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="#">{{ object.owner }}</a>
	      <small class="text-muted">{{ object.created_at|date:"F d, Y" }}</small>
	      	{% if request.user == object.owner %}
	        		<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'myarts:article-update' object.id %}">Update</a>
	        		<a class="btn btn-danger btn-sm mt-1 mb-1 " href="{% url 'myarts:article-delete' object.id %}">Delete</a>

	   		{% endif %}
	    </div>
	    <h2 class="article-title">{{ object.title }}</h2>
	    <p class="article-content">{{ object.text }}</p>
	   	  </div>
	  
	</article>
{% endblock content %}

dj4e_2/myarts/templates/myarts/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Article</legend>
				{{ form|crispy }}
				
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
			</div>
		</form>
	</div>
{% endblock content %}

dj4e_2/myarts/templates/myarts/article_list.html
{% extends 'base.html' %}
{% block navbar %} 
<a class="nav-item nav-link" href="{% url 'myarts:article-create' %}">New Article</a>   	
{% endblock %}
{% block content %}


	<h1>Articles</h1>
	{% if article_list %}
		{% for article in article_list %}
			<article class="media content-section">
			  <div class="media-body">
			    <div class="article-metadata">
			      <a class="mr-2" href="#">{{ article.owner }}</a>
			      <small class="text-muted">{{ article.created_at|date:"F d, Y" }}</small>
			    </div>
			    <h2><a class="article-title" href="{% url 'myarts:article-detail' article.id %}">{{ article.title }}</a></h2>
			    <p>{{ article.text }}</p>
			  </div>
			</article>
		{% endfor %}
	{% else %}
		There are no article items at this moment.
	{% endif %}

{% endblock content %}