dj4e_2/ad/urls.py
from django.urls import path
from . import views

app_name='ads'
urlpatterns = [
	path('', views.AdListView.as_view(), name='main'),
	path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad-detail'),
	path('ad/create/', views.AdCreateView.as_view(), name='ad-create'),
	path('ad/<int:pk>/update/', views.AdUpdateView.as_view(), name='ad-update'),
	path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(), name='ad-delete'),
	path('pic_picture/<int:pk>/', views.stream_file, name='pic_picture'),
]

dj4e_2/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
import os
from django.views.static import serve


urlpatterns = [
	path('', include('home.urls')),
    path('myarts/', include('myarts.urls')),
    path('ads/', include('ad.urls')),
    path('forum/', include('forum.urls')),
    path('jsonapp/', include('jsonapp.urls')),
    # path('pics/', include('pics.urls')), replaced by ad app
    path('admin/', admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('register/', user_views.Register.as_view(), name="register"),
]
# server favicon
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('favicon.ico', serve, {
            "path":"favicon.ico",
            "document_root": os.path.join(BASE_DIR, "home/static"),
        } 
        ),

]

dj4e_2/ad/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
# Create your models here.
class Ad(models.Model):
	title = models.CharField(max_length=200,
		validators = [MinLengthValidator(2, "Please Enter atlease 2 character")]
		)
	price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
	text = models.TextField()
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	# picture field as Binary Field
	picture = models.BinaryField(editable=True, null=True, blank=True)
	content_type = models.CharField(max_length=256, null=True, blank=True,
		help_text="The MIMEtype of file")
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.title

dj4e_2/ad/forms.py
from django import forms
from .models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import natural_size


class CreateForm(forms.ModelForm):
	max_upload_limit = 2 * 1024 * 1024
	max_upload_limit_text = natural_size(max_upload_limit)
	#  picture is here in memory onject 'picture' is corresponding feild name
	# to be used for form
	picture = forms.FileField(required=False, label='File to upload < ' + max_upload_limit_text)
	upload_field_name = 'picture'


	class Meta:
		model = Ad
		fields = ['title', 'price', 'text', 'picture']


	def clean(self):
		cleaned_data = super().clean()
		pic = cleaned_data.get('picture')
		if pic is None:
			return 
		if len(pic) > self.max_upload_limit:
			self.add_error('picture', 'File must be < ' + self.max_upload_limit_text + ' bytes')

	# convert uploaded file into picture
	def save(self, commit=True):
		print('hi')
		instance = super(CreateForm, self).save(commit=False)
		pic = instance.picture
		if isinstance(pic, InMemoryUploadedFile):
			bytearr = pic.read()
			instance.content_type = pic.content_type
			instance.picture = bytearr
			print('4')

		if commit:
			print('comiting')
			instance.save()
		print('5')
		return instance

dj4e_2/ad/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View 
from django.views.generic import (
	CreateView,
	UpdateView,
	DetailView,
	DeleteView,
	ListView
	)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile
from .models import Ad
from django.http import HttpResponse
from .forms import CreateForm
# Create your views here.


class AdListView(ListView):
	model = Ad

class AdDetailView(DetailView):
	model = Ad

class AdCreateView(LoginRequiredMixin, View):
	template_name = 'ad/ad_form.html'
	success_url = reverse_lazy('ads:main')

	def get(self, request):
		form = CreateForm()
		context = {
		'form': form
		}
		return render(request, self.template_name, context)

	def post(self, request):
		form = CreateForm(request.POST, request.FILES or None)

		if not form.is_valid():
			context = {
			'form':form
			}
			return render(request, self.template_name, context)
		print("This ran")
		form.instance.owner = self.request.user
		print('1')
		form.save()
		print('6')
		return redirect(self.success_url)

class AdUpdateView(LoginRequiredMixin, View):
	template_name = 'ad/ad_form.html'
	success_url = reverse_lazy('ads:main')
	def get(self, request, pk):
		ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
		form = CreateForm(instance = ad)
		context = {
		'form': form
		}
		return render(request, self.template_name, context)

	def post(self, request, pk):
		ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
		form = CreateForm(request.POST, request.FILES or None, instance=ad)

		if not form.is_valid():
			ctx = {'form': form}
			return render(request, self.template_name, ctx)
		print('1')
		print(type(form.instance))
		# <class 'ad.models.Ad'>

		form.save()

		

		return redirect(self.success_url)



class AdDeleteView(DeleteView):
	model = Ad
	success_url = reverse_lazy('ads:main')
	def get_queryset(self):
		qs = super(AdDeleteView, self).get_queryset()
		return qs.filter(owner=self.request.user)



def stream_file(request, pk):
	ad = get_object_or_404(Ad, id=pk)
	response = HttpResponse()
	response['Content-Type'] = ad.content_type
	response['Content-Length'] = len(ad.picture)
	response.write(ad.picture)
	return response

dj4e_2/ad/templates/ad/ad_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete Ad</h1>
<p>Are you sure you want to delete the ad : {{ad}}? </p>
<form action="" method="POST">
	{% csrf_token %}
	<input type="submit" value="Yes, delete.">
</form>
{% endblock content %}

dj4e_2/ad/templates/ad/ad_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block head %}
<style>
	.overlay{
		position:fixed;
		top:0;
		left:0;
		width:100%;
		height:100%;
		z-index: 40;
		display: none;
		background-color: rgba(0,0,0, 0.5);
	}
	.center-fit{
		max-width: 100%;
		max-height: 100vh;
		margin:auto;
		padding: 5vh;
	}
</style>
{% endblock head %}
{% block content %}
{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align:center;"
onclick="document.getElementById('overlay').style.display='none';">
<img class="center-fit" src="{% url 'ads:pic_picture' ad.id %}">
</div>
{% endif %}
<span style="float:right;">
	({{ ad.updated_at|naturaltime}})
	{% if ad.owner == user %}
	<a href="{% url 'ads:ad-update' ad.id %}"><i class="fa fa-pencil">edit</a>
	<a href="{% url 'ads:ad-delete' ad.id %}"><i class="fa fa-trash">Delete</a>
	{% endif %}
</span>
<h1>
	{{ad.title}}
</h1>
{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:pic_picture' ad.id %}" onclick="document.getElementById('overlay').style.display='block;">
{% endif %} 
<p>
{{ ad.text }}
</p>
{% endblock content %}

dj4e_2/ad/templates/ad/ad_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<p>
	<form action="" method="post" id="upload_form" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="submit">
		<input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:main' %}'; return false;">
	</form>
</p>

<script>
	$('#upload_form').submit(function(){
		console.log('Checking file size');
		if(window.File && window.FileReader && window.FileList && window.Blob){
			var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
			if (file && file.size > {{ form.max_upload_limit }}){
				alert("File" + file.name + "of type" + file.type + "must be < {{ form.max_upload_limit_text }}");
				return false;
			}
		}
	});
</script>
{% endblock content %}

dj4e_2/ad/templates/ad/ad_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Ads</h1>
<p>
	{% if ad_list %}
	<ul>
		{% for ad in ad_list %}
		<li>
			<a href="{% url 'ads:ad-detail' ad.id %}">{{ad.title}}</a>
			{% if ad.owner == user %}
			(<a href="{% url 'ads:ad-update' ad.id %}">Edit</a> | 
			<a href="{% url 'ads:ad-delete' ad.id %}">Delete</a>)
			{% endif %}
		</li>
		{% endfor %}
	</ul>
	{% else %}
	There are no ads in the database
	{% endif %}
</p>
<p>
	<a href="{% url 'ads:ad-create' %}">Add an ad</a>
</p>
{% endblock content %}